# FVM support
sdkPath: .fvm/flutter_sdk

name: hisma

repository: https://github.com/tamas-p/hisma

packages:
  - packages/*
  - examples/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze --fatal-infos .
    exec:
      concurrency: 1
    
  doc:
    run: dart doc
    exec:
      concurrency: 1
  
  pana:
    run: pana --no-warning --exit-code-threshold=0 .
    select-package:
      no-private: true
    exec:
      concurrency: 1

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this monorepo for all packages.

  test:dart:
    run: melos exec -c 1 "dart pub global run coverage:test_with_coverage"
    description: Run Dart tests for a specific package in this monorepo.
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: melos exec --dir-exists="test" -c 1 "flutter test --coverage"
    description: Run Flutter tests for a specific package in this monorepo.
    select-package:
      flutter: true
      dir-exists: test

  lcov:genhtml:
    run: melos exec -c 1 "genhtml ./coverage/lcov.info -o coverage/html/"
    description: Generate code coverage HTML report.
    select-package:
      dir-exists: coverage

  lcov:list:
    run: melos exec -c 1 "lcov --list ./coverage/lcov.info"
    description: Generate code coverage report.
    select-package:
      dir-exists: coverage

  upgrade:
    run: melos run upgrade:dart && melos run upgrade:flutter
    description: Run all Dart & Flutter package upgrades.

  upgrade:dart:
    run: melos exec -c 1 "dart pub upgrade"
    description: Run Dart pub upgrade a specific package in this monorepo.
    select-package:
      flutter: false

  upgrade:flutter:
    run: melos exec -c 1 "flutter pub upgrade"
    description: Run Flutter pub upgrade for a specific package in this monorepo.
    select-package:
      flutter: true