name: visma
description: Visma is visualizing Hisma state machines in the web browser.
homepage: https://github.com/tamas-p/hisma
repository: https://github.com/tamas-p/hisma/tree/master/packages/visma
version: 0.1.2+1

executables:
  visma:

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.1
  hisma_visual_monitor: ^0.3.1+2
  logging: ^1.1.0
  pumli: ^0.1.1

dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
